### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DiaxManPl** [Mati365/librus-api#19]
Is there any option for getting account name? For example I have account with login **138372972892782**, but my name is **DiaxManPl**.

**Comment by Mati365** [comment]
Możesz pisać po polsku jakby co. Nie ma takiej opcji, jednakże jeśli zrobisz PRkę, która odczyta z contentu strony takową to będę wdzięczny (inni zapewne też).

**Comment by DiaxManPl** [comment]
Okej. A takie pytanie debila: Co to PRka?

**Comment by Mati365** [comment]
@DiaxManPl zrób forka libki, dodaj metodę do api, potem kliknij create pull request i wybierz tam swojego forka do porównania. Po utworzeniu sprawdzę czy nie wysadziłeś przypadkiem czegoś w kosmos, mergnę i opublikuję libkę

**Comment by DiaxManPl** [comment]
Okej. Już nawet widzę jak.

**Comment by DiaxManPl** [comment]
Dbr sry, nie umiem się połapać w twoim kodzie. Powiem tylko, że url to: https://synergia.librus.pl/informacja. Poniżej znajdziesz listę selektorów, które mogą się przydać:
- imie i nazwisko ucznia: `#body > div > div > table > tbody > tr:nth-child(1) > td`
- klasa: `#body > div > div > table > tbody > tr:nth-child(2) > td`
- nr w dzienniku: `#body > div > div > table > tbody > tr:nth-child(3) > td`
- wychowawca: `#body > div > div > table > tbody > tr:nth-child(4) > td`
- imię i nazwisko konta: `#body > div > div > table > tbody > tr:nth-child(7) > td`
- login: `#body > div > div > table > tbody > tr:nth-child(8) > td`

**Comment by Mati365** [comment]
@DiaxManPl nie mam dostępu do platformy synergii od kilku lat, nie mam jak tego zmienić. Odnośnie metod - w bibliotece, którą podlinkowalem w libce (cheerio) - bez problemu możesz odczytać te selektory używając np `$(..selektor..).text()`

**Comment by DiaxManPl** [comment]
Ok. Powiedz tylko jakiej twojej metody użyć. Bo tam jest kilka, a ja nie za bardzo je rozumiem.

**Comment by Mati365** [comment]
https://github.com/Mati365/librus-api/blob/master/lib/resources/info.js#L136

zerknij na tą metodę. Ona pobiera Ci stronę pod podaną ścieżką, wybiera jakiś element i odpala parser. Być może takie coś podziała:
```js
  getAccountInfo(){
	let parser = ($,element) => {
		return {
		   nameSurname: $('#body > div > div > table > tbody > tr:nth-child(1) > td').text()
		   , .....
		};
	}
	return this.api._singleMapper(
	  'informacja'
	, "html"
	, parser
	);
   }
```

**Comment by DiaxManPl** [comment]
Ok napisane. Ostatnie poprawki

**Comment by DiaxManPl** [comment]
Dobra. Wyświetla mi się, że jeszcze ostatnie sprawdzanie pull requesta trwa.

**Comment by Mati365** [comment]
Super, wieczorem wrzucę do npma

**Comment by DiaxManPl** [comment]
Ok fajnie

**Comment by DiaxManPl** [comment]
Nadal nid ma

**Comment by Mati365** [comment]
Już Ide klikać

**Comment by Mati365** [comment]
@DiaxManPl Opublikowane w wersji 2.4.2

**Comment by DiaxManPl** [comment]
No i kozak

**Comment by DiaxManPl** [comment]
Ja nadal tego nie mam. 
![image](https://user-images.githubusercontent.com/63294962/110371038-b8ba0280-804c-11eb-9a11-54e9259be826.png)
