### ISSUE TITLE
Błąd w getNotifications()

### ISSUE THREAD

**Issue by DiaxManPl** [Mati365/librus-api#21]
Api z niewiadomych przyczyn nie jest w stanie odczytać poprawnie powiadomień. Mnie na librusie pokazuje, że mam 3 powiadomienia, a api pokazuje 1. Próbowałem to naprawić, lecz nie umiem.

**Comment by Mati365** [comment]
sprawdź czy dobry element jest parsowany

**Comment by DiaxManPl** [comment]
Sprawdziłem. To nie w tym problem.

**Comment by DiaxManPl** [comment]
Naprawione
