### ISSUE TITLE
getEvent() returns 0

### ISSUE THREAD

**Issue by itsokk** [Mati365/librus-api#24]
title, lmk if i should provide more info

**Comment by Mati365** [comment]
niestety nie mam dostępu do librusa, jeśli możesz to plz zrób w wolnym czasie PRkę z fixem na to. zmerguję

**Comment by CodeKid0** [comment]
> niestety nie mam dostępu do librusa, jeśli możesz to plz zrób w wolnym czasie PRkę z fixem na to. zmerguję

login: demorodzic
hasło: librus11

**Comment by lukasz-wronski** [comment]
Tutaj fix: https://github.com/Mati365/librus-api/pull/67 - możesz @Mati365 merdżować

**Comment by Mati365** [comment]
@lukasz-wronski Dzięki za fixa! Wrzuciłem w wersji `2.12.0` :tada:
