### ISSUE TITLE
Nie działa logowanie

### ISSUE THREAD

**Issue by mccartney** [Mati365/librus-api#3]
Po zmianach tego lata - logowanie do Librusa przestało działać.

Poprawiłem w swoim forku:
https://github.com/mccartney/librus-api/commit/732d73f11aaac3770f6673b8c201419cbc3dcd14
(niezbyt elegancko, bo hardcode'ując URLe)

Ale może komuś się przyda...

**Comment by Mati365** [comment]
Dzięki, przygotowałbyś pull request ze zmianami? Chętnie mergnąłbym(od paru lat nie mam dostępu do librusa ;) )

**Comment by mccartney** [comment]
W wolnej chwili zrobię.
Przy okazji - można w Internecie znaleźć dostęp testowy - np. http://web.archive.org/web/20160720183212/https://www.zssucha.pl/szkola/content/skf-librus-wersja-demonstracyjna
