### ISSUE TITLE
Problem z Ocenami

### ISSUE THREAD

**Issue by 6vz** [Mati365/librus-api#33]
# Gdzie jest problem?
Przy poproszeniu o wszystkie oceny, zwracane jest "kurwa nic"<br>
# Wynik Programu
![](https://imgs.today/2/QXdcBNc6YE5R298.png)<br>
# Kod
```js
const Librus = require("librus-api");
require('dotenv').config()
const env = process.env

let client = new Librus();
client.authorize(process.env.LIBRUS_LOGIN, process.env.LIBRUS_PASSWD).then(function () {
    client.info.getGrades().then(data => console.log(data));
})
```
<br>

# Dodatkowe Informacje
Potrzebuje szybko tych danych, żebym mógł ich używać w integracji 🥶 
Szybka odpowiedz będzie mile widziana oraz doceniona ⭐

**Comment by Mati365** [comment]
Niestety nie mam dostępu do Librusa i nie jestem w stanie tego naprawić. Jeśli uda Ci się to naprawić to, w imieniu osób które używają tej libki, byłbym wdzięczny za PRkę.

**Comment by 6vz** [comment]
To tylko moja głupota, już mnie ludzie poprawiają i opierdalają na moim Discordzie, wszystko jest dobrze (i think)

**Comment by oceaann** [comment]
> To tylko moja głupota, już mnie ludzie poprawiają i opierdalają na moim Discordzie, wszystko jest dobrze (i think)

Dokładnie, console.log ma limity przy wyświetlaniu obiektów, zawsze możesz skorzystać z `JSON.stringify`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify
