### ISSUE TITLE
request-promise has been deprecated

### ISSUE THREAD

**Issue by mccartney** [Mati365/librus-api#37]
https://www.npmjs.com/package/request-promise podaje:

> request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

Na razie nie wiem, czy to w czymś przeszkadza. Przez wakacje przestało mi działać - jestem w trakcie debugowania.

**Comment by Mati365** [comment]
Nie mam dostępu do librusa :( jeśli uda Ci się to poprawić to zrób proszę PRkę, z pewnością innym się przyda

**Comment by DiaxManPl** [comment]
Sorry, za necro posting, ale pracuję nad projektem skupiającym w sobie różne API, więc jeśli komuś by się udało przepisać to API na nową paczkę, taką jak np. [axios](https://www.npmjs.com/package/axios), byłbym bardzo wdzięczny. Ja sam próbowałem, ale ciągle wyrzucało mi brak uprawnień. Nie mam pojęcia, dlaczego ze starą paczką to działa a z axiosem nie. Najprawdopodobniej jest to jakiś problem z plikami cookies, ale nie znam się na tym na tyle, żeby móc skutecznie debugować. Jeśli komuś by się udało albo przyszło mu do głowy jakieś rozwiązanie, piszcie o tym tutaj. 
Trzymajcie się cieplutko,
Diaxu.

**Comment by DiaxManPl** [comment]
Wydaje mi się, że mamy sukces. Pracuję nad PRką.

**Comment by DiaxManPl** [comment]
#50

**Comment by DiaxManPl** [comment]
#50
