### ISSUE TITLE
Node-Red

### ISSUE THREAD

**Issue by QBANIN** [Mati365/librus-api#43]
Cześć. Jest szansa zrobić z tego moduł do Node-Red?

**Comment by Mati365** [comment]
Nigdy tego nie używałem :( jeśli uda Ci się dograć projekt w tym narzędziu to zrób proszę PRkę a zmerguję

**Comment by jaroslaw81** [comment]
Nie ma takiej potrzeby NR normalnie importuje npm i można używać. Dodam, że sam korzystam i działa ok.
