### ISSUE TITLE
getMessage nie zwawiera `files`

### ISSUE THREAD

**Issue by koliwbr** [Mati365/librus-api#47]
`getMessage()` bezproblemowo podaje tytuł, treść czy inne pierdoły ale nie ma pola file które pozwalało by na pobranie plików

**Comment by swiergot** [comment]
U mnie nadal działa. Sprawdź ten kod (u mnie `861745` to losowa wiadomość zawierająca załączniki):

```
  client.authorize(user, pass).then(function () {
    client.inbox.listInbox(5).then(data => {
      for (const message of data) {
        const msgid = message.id;

        if (msgid === 861745) {
          client.inbox.getMessage(5, msgid).then(details => {
            console.log(details.files);
          });
        }
      }
    });
  });
```

**Comment by koliwbr** [comment]
Masz jakieś demo? U mnie wiadomość która ma załącznik (jednego pdf'a) nie zwraca ani Array pusty [] ani Array z plikiem [{'nazwa':'plik.pdf','link':'https://example.com/pliczek.pdf'}]

details.files zwraca undefined

23 paź 2022 07:42:43 Jarek Świerczyński ***@***.***>:

**Comment by swiergot** [comment]
To ciekawe, bo u mnie w przypadku wiadomości bez załączników zwraca pustą tablicę. Na pewno masz najnowszą wersję biblioteki?

**Comment by koliwbr** [comment]
aaaa racja, cała 'dokumentacja' jest w [README.md](https://github.com/Mati365/librus-api/blob/master/README.md) i miła by była informacja o tym kiedy dodano daną opcja.

Tak czy siak, dzięki za pomoc, mój błąd
