### ISSUE TITLE
Errors instantly after executing file

### ISSUE THREAD

**Issue by malak4822** [Mati365/librus-api#54]
Hi, i executed file (usage.js) with command `node usege.js` and those are the things which were shown to me.
How to check if i am really connected, logged in and i am in librus panel? How can i retrieve entire body from there? 
```
/.../Librus-Frequency/librus_api/node_modules/axios/dist/node/axios.cjs:836
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError: connect ECONNREFUSED ::1:80
    at AxiosError.from (/.../Librus-Frequency/librus_api/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/.../Developer/Librus-Frequency/librus_api/node_modules/axios/dist/node/axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/.../Librus-Frequency/librus_api/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at req.emit (/.../Librus-Frequency/librus_api/node_modules/http-cookie-agent/dist/http/create_cookie_agent.js:84:16)
    at Socket.socketErrorListener (node:_http_client:494:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
```
Thank you very much for sharing this api <3

**Comment by Mati365** [comment]
Hejka, w example powinieneś mieć całą foremkę pod to.

https://github.com/Mati365/librus-api/tree/master#usage

```tsx
const Librus = require("librus-api");

let client = new Librus();
client.authorize("login", "pass").then(function () {
    ....
});
```

**Comment by malak4822** [comment]
> Hejka, w example powinieneś mieć całą foremkę pod to.
> 
> https://github.com/Mati365/librus-api/tree/master#usage
> 
> ```tsx
> const Librus = require("librus-api");
> 
> let client = new Librus();
> client.authorize("login", "pass").then(function () {
>     ....
> });
> ```

No cały ten plik wkleiłem ale te błędy wywala, powinno śmigać jak pobiore pakiet (npm install librus-api), zmienię dane librusa w tych dwóch polach z autoryzacją i go wywołam (node usage.js), dobrze rozumiem?

**Comment by Mati365** [comment]
Tak. Wygląda jakby odpytywało Ci zly adres URL w librusie. Możesz wejść w node_modules i dać ręcznie console.log w paru miejscach paczki by upewnić się, że coś jest nie tak. Może coś zmieniono w samym librusie 🤷🏻 Byłbym wdzięczny za ewentualną PRkę z fixem - nie mam od dawna dostępu do librusa.

**Comment by malak4822** [comment]
![image](https://github.com/Mati365/librus-api/assets/71153710/a47e6d94-45c7-401e-b0d5-f02f95aa4f87)

Hej, nie masz może chwili mi pomóc? Nie działa jedna funkcja, której akurat potrzebuje [getTimetable()] (potrzebuje info o tym ile jest lekcji w tygodniu czyli dostać się do planu lekcji), po wywołaniu tej funkcji wywala błąd (w linku)  
Co zrobiłem:
w pliku axios.cjs podmieniłem http://localhost na https://synergia.librus.pl, wydawało mi się to bardziej logiczne, wtedy wyskoczył kolejny błąd (w linku), dasz radę jakoś pomóc?
 (https://codeshare.io/nzeNQV)

**Comment by Delwing** [comment]
@malak4822 wydaje mi się, że naprawiłem ten błąd, u mnie na ten moment już to działa, plan już się wyświetla na wallpanelu :) Issue powinno być do zamknięcia.
