### ISSUE TITLE
Axios errror / zmiana headerów

### ISSUE THREAD

**Issue by Simciutoja** [Mati365/librus-api#63]
Podczas próby połączenia z librusem, wyskakują same błedy na temat axiosa.

**Aktualny kod** 

``` typescript
  const Librus = require("librus-api");
    let client = new Librus();
    client.authorize(name, password).then(() => {
        console.log("Logged in");
    }).catch((err: any) => {
        console.error(err);
    });
```

**Błąd** 

(Login in daje siępoprzez kod, ale nie wiem czemu bo nie chce się zalogować defacto)
![image](https://github.com/Mati365/librus-api/assets/120786782/63ded724-ef7a-424d-9091-02efc72c2a74)

**Comment by Mati365** [comment]
Sorka, zapomniałem odpisać. Linki musisz używać z poziomu Node, ze względu na CORSy
