### ISSUE TITLE
inbox.js broken

### ISSUE THREAD

**Issue by pituluk** [Mati365/librus-api#64]
```
librus-api/lib/resources/inbox.js:173
        id: parseInt($(children[3]).find("a").attr("href").split(/[/]/)[4]),
                                                          ^

TypeError: Cannot read properties of undefined (reading 'split')

```

**Comment by Mati365** [comment]
Hejka, nie mam dostępu do librusa od wielu lat. Pewnie zmieniło się coś w strukturze HTML i padło. Byłbym wdzięczny jakbyś podrzucił fix ;)

**Comment by pituluk** [comment]
chetnie bym naprawil ale obecnie jest poczatek roku i nie ma wiadomosci, struktura wyglada na poprawna? nie rozumiem tylko czemu parser ma na stale wpisane offsety w array i nie rozumiem co ta crashujaca linia ma robic

**Comment by Mati365** [comment]
W czwartym segmencie linku jest numeryczny ID, stąd na sztywno zanotowany indeks

**Comment by pituluk** [comment]
nie rozumiem co zrobila ta zmiana z commita cheerio ale naprawilo sie :)

**Comment by Mati365** [comment]
Oki
