### ISSUE TITLE
Poprawione pobieranie ogłoszeń

### ISSUE THREAD

**Issue by MichalTcz** [Mati365/librus-api#8]
propozycja zmiany w inbox.js
173c173
```
<       , "form[name='formOgloszenia'] table.decorated.form"
---
>       , "table.decorated"
```

**Comment by Mati365** [comment]
Zrób jak możesz pull request, mergnę zmiany i bumpnę wersję w NPM.

**Comment by MichalTcz** [comment]
Mój pierwszy :)

**Comment by Mati365** [comment]
@MichalTcz nie mam dostępu do githuba ale wydaje mi się, ze selektor jest zbyt ogólny. Zauważyłem to dopiero po merge xD mógłbyś go nieco bardziej sprecyzować na ten element?

**Comment by MichalTcz** [comment]
Zrobione.

**Comment by Mati365** [comment]
Dzięki! Zmergowałem zmiany :D
